language: node_js
node_js: 5

before_script:
  - cd client
  - npm install
script:
  - npm test

cache:
  directories:
    - ~/.npm
    - ~/.node-gyp
    - node_modules

notifications:
  irc:
    nick: chat
    channels: 'ircs://irc.uriirc.org:16664#hyeon'
    template: '#%{build_number} %{result}, %{build_url}'
    skip_join: true
